/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.gobenow.home;

public final class R {
    public static final class array {
        public static final int gender=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int birthdate=0x7f060011;
        public static final int birthdate_view=0x7f060010;
        public static final int button1=0x7f060000;
        public static final int button2=0x7f060001;
        public static final int firstname_edit=0x7f06000b;
        public static final int firstname_view=0x7f06000a;
        public static final int gender=0x7f060013;
        public static final int gender_view=0x7f060012;
        public static final int lastname_edit=0x7f06000d;
        public static final int lastname_view=0x7f06000c;
        public static final int linearLayout1=0x7f060009;
        public static final int password__confirmation_view=0x7f06000e;
        public static final int password_confirmation_edit=0x7f06000f;
        public static final int password_edit=0x7f060005;
        public static final int password_view=0x7f060004;
        public static final int scrollView1=0x7f060008;
        public static final int sign_in=0x7f060006;
        public static final int sign_up=0x7f060007;
        public static final int username_edit=0x7f060003;
        public static final int username_view=0x7f060002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int sign_in=0x7f030001;
        public static final int sign_up=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int birthdate=0x7f040007;
        public static final int firstname=0x7f040004;
        public static final int gender=0x7f040008;
        public static final int hello=0x7f040000;
        public static final int lastname=0x7f040005;
        public static final int password=0x7f040003;
        public static final int password_confirmation=0x7f040006;
        public static final int username=0x7f040002;
    }
}
